
version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: dotnet tool install --global PowerShell@7.0.3
      - run: pwsh ./<my-script>.ps1

